name: .NET Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
          export GitHub__ClientId="${{ secrets.GITHUBCLIENTID }}"
          export GitHub__ClientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
          dotnet test --no-build --verbosity normal
    - name: Install Playwright
      run: |
        npm install -D playwright
        pwsh -Command "Chirp.Web/bin/Debug/net8.0/playwright.ps1 install --with-deps"

    - name: Run Playwright Tests
      run: npx playwright test --headed
