name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
      # Restore
    - name: Restore dependencies
      run: dotnet restore
      
      # Build
    - name: Build
      run: dotnet build --no-restore
      
      # Test
    - name: Test
      run: |
        export authentication_github_clientId="${{ secrets.GITHUBCLIENTID }}"
        export authentication_github_clientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
        dotnet test --no-build --verbosity normal
      
      # Publish for Linux
    - name: Publish Linux
      run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -r linux-x64 -o publish/linux-x64
      
      # Zip Linux artifacts
    - name: Zip Linux Artifacts
      run: zip -r Chirp_linux-x64.zip publish/linux-x64
      
      # Publish for Windows
    - name: Publish Windows
      run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -r win-x64 -o publish/win-x64
      
      # Zip Windows artifacts
    - name: Zip Windows Artifacts
      run: zip -r Chirp_win-x64.zip publish/win-x64
      
      # Publish for MacOS x64
    - name: Publish MacOS x64
      run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -r osx-x64 -o publish/osx-x64
      
      # Zip MacOS x64 artifacts
    - name: Zip MacOS x64 Artifacts
      run: zip -r Chirp_osx-x64.zip publish/osx-x64
      
      # Publish for MacOS ARM
    - name: Publish MacOS ARM
      run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -r osx-arm64 -o publish/osx-arm64
      
      # Zip MacOS ARM artifacts
    - name: Zip MacOS ARM Artifacts
      run: zip -r Chirp_CLI_osx-arm64.zip publish/osx-arm64

      # Create release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Chirp_linux-x64.zip
          Chirp_win-x64.zip
          Chirp_osx-x64.zip
          Chirp_osx-arm64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
