name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup2chirpremotedb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Build with dotnet
        run: dotnet build src/CSVDBService/ --configuration Release

      - name: dotnet publish
        run: dotnet publish src/CSVDBService/ -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FEB48E7F659E4B2A8FE083E92A6DB0DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2CB3029D3BD24C7EA134FE7C25CD4F98 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27E2F68EC4F94C25861FA0B53C03DDED }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup2chirpremotedb'
          slot-name: 'Production'
          package: ./myapp
