name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Linux
      run: 
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -r linux-x64 -o publish/linux-x64
        zip -r Chirp_CLI_linux-x64.zip publish/linux-x64
    - name: Publish Windows
      run: 
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -r win-x64 -o publish/win-x64
        zip -r Chirp_CLI_win-x64.zip publish/win-x64
    - name: Publish MacOS x64
      run: 
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -r osx-x64 -o publish/osx-x64
        zip -r Chirp_CLI_osx-x64.zip publish/osx-x64
    - name: Publish MacOS ARM
      run: 
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -r osx-arm64 -o publish/osx-arm64
        zip -r Chirp_CLI_osx-arm64.zip publish/osx-arm64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: "Chirp*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
